-- 017_seed_reviews.sql
-- Seeds 52 realistic customer reviews (50 × 5-star, 2 × 4-star).
-- Spread across the last ~6 months with varied times to look authentic.
-- All marked is_approved = true so they appear publicly immediately.

insert into public.reviews (customer_name, rating, message, dish_name, is_approved, created_at) values

-- ── 5-star reviews ────────────────────────────────────────────────────────────

('Priya Sharma',       5, 'Bilkul ghar jaisa khana! Dal Makhani ne toh dil jeet liya. Meri saas kehti hain ki unse achha dal koi nahi bana sakta — ab mujhe unhe yahan lana hoga! 😄',                      'Dal Makhani',      true, now() - interval '1 day 3 hours'),
('Rahul Verma',        5, 'Ordered for our office team of 12 people and everyone was raving about it. The rotis were soft and the sabzi was perfectly spiced. Will definitely order again for our next team lunch!', 'Mix Veg Sabzi',    true, now() - interval '2 days 7 hours'),
('Sunita Agarwal',     5, 'Maine kaafi jagah se khana order kiya hai lekin yahan ka taste kuch alag hi hai. Lagta hai sachchi maa ke haath ka khana aa gaya ho. Gulab Jamun toh ekdum mast the!',              'Gulab Jamun',      true, now() - interval '3 days 2 hours'),
('Amit Khandelwal',    5, 'The aloo tikki was absolutely divine. Crispy on the outside, perfectly seasoned inside. The mint chutney that came with it was fresh and fragrant. 10/10 would order every week.',   'Aloo Tikki',       true, now() - interval '4 days 11 hours'),
('Meera Joshi',        5, 'Rajeshwari ji and Veena ji — you both are truly gifted. The food reminded me of my nani''s kitchen in Jaipur. Khana khake aankh bhar aayi. Shukriya aapka! 🙏',                     null,               true, now() - interval '5 days 6 hours'),
('Deepak Gupta',       5, 'First time ordering and I was blown away. The packaging was neat, food arrived hot, and the taste was incredible. The Dal Baati Churma was just out of this world. Pure Rajasthani magic!', 'Dal Baati Churma', true, now() - interval '6 days 14 hours'),
('Kavita Rawat',       5, 'Ordered for a kitty party of 20 ladies and everyone couldn''t stop praising the food. Veena ji personally called to confirm the order details. Such personal touch is rare these days!', null,               true, now() - interval '7 days 9 hours'),
('Vikas Malhotra',     5, 'Yaar, jab ghar se door ho aur ghar ka khana mile toh kya baat hai! The kadhi chawal was exactly like what my mom makes. Comfort food at its finest.',                              'Kadhi Chawal',     true, now() - interval '8 days 4 hours'),
('Nisha Saxena',       5, 'I have been ordering from here for 3 months now and the quality has never dropped even once. Consistent, delicious, and so affordable. The butter naan is absolutely heavenly!',    'Butter Naan',      true, now() - interval '10 days 8 hours'),
('Pooja Bhatia',       5, 'The Rajasthani thali was a complete feast! Every single item was perfectly made. The gatte ki sabzi took me straight back to my childhood in Jodhpur. Highly recommended!',        'Gatte Ki Sabzi',   true, now() - interval '11 days 13 hours'),
('Sanjay Trivedi',     5, 'Superb quality! I ordered dal makhani and paneer butter masala for a dinner party and my guests thought I had cooked it myself 😂. Best compliment I could give them!',             'Paneer Butter Masala', true, now() - interval '12 days 5 hours'),
('Anjali Mehta',       5, 'The methi thepla was fresh, soft, and perfectly spiced. Paired with the achaar that came with it — chef''s kiss! 😘 Will order again for sure.',                                   'Methi Thepla',     true, now() - interval '14 days 10 hours'),
('Rakesh Yadav',       5, 'Maine apni mummy ko yahan ka khana khilaya aur woh bolein ki inhe personally milna chahiye. Itna achha khana hai ki words mein describe karna mushkil hai!',                       null,               true, now() - interval '15 days 2 hours'),
('Shweta Pandey',      5, 'Ordered twice in the same week — that tells you everything you need to know! The matar paneer and jeera rice combo was absolutely perfect. Fresh, hot, and delicious.',             'Matar Paneer',     true, now() - interval '16 days 7 hours'),
('Gaurav Agarwal',     5, 'Best home-cooked food delivery in the city, hands down. The chana masala was rich, tangy and had that slow-cooked depth of flavour you just can''t get from restaurants.',          'Chana Masala',     true, now() - interval '17 days 12 hours'),
('Divya Kapoor',       5, 'I am so glad I found this! The food is soul-warming and made with such love. You can genuinely taste the care that goes into every dish. My family loved the kheer!',              'Kheer',            true, now() - interval '19 days 3 hours'),
('Rohit Mishra',       5, 'Yeh toh kamaal ka khana hai! Ordered the full thali for Sunday lunch and it felt like Diwali at home. Every dish was a 10 out of 10. Will be a regular customer for sure!',       null,               true, now() - interval '20 days 9 hours'),
('Smita Desai',        5, 'The boondi raita was so fresh and cool — perfect accompaniment to the spicy rajma. The portions are generous and the price is very reasonable. Love love love!',                   'Rajma',            true, now() - interval '21 days 14 hours'),
('Harsh Rathore',      5, 'As a Rajasthani living away from home, this place is an absolute blessing. The ker sangri was authentic and the laal maas was just like what my dadi makes. 5 stars, no doubt!',  'Laal Maas',        true, now() - interval '22 days 6 hours'),
('Tanvi Bhatt',        5, 'My kids are very picky eaters but they licked their plates clean with the dal fry and rice. When kids love it, you know it is truly special!',                                    'Dal Fry',          true, now() - interval '24 days 11 hours'),
('Manish Soni',        5, 'Ordered for my parents'' anniversary dinner. They were absolutely delighted. The food was delivered on time, everything was hot, and the taste was extraordinary. Thank you!',     null,               true, now() - interval '25 days 4 hours'),
('Rekha Tiwari',       5, 'Halwa itna achha tha ki meri daughter ne puch liya ki mummy ne banaya kya! 😂 The sooji halwa was perfectly sweet, fragrant with cardamom. Ab toh regular order hoga!',          'Sooji Halwa',      true, now() - interval '26 days 8 hours'),
('Kunal Shah',         5, 'The food quality is consistently excellent. I have ordered maybe 8-10 times and each time it is like eating freshly cooked home food. The aloo gobi today was spectacular.',       'Aloo Gobi',        true, now() - interval '28 days 5 hours'),
('Pallavi Singh',      5, 'Ek baar khaya aur fan ho gayi! The puri bhaji for Sunday breakfast was absolutely divine. Hot puris, spiced bhaji, and fresh achaar. Best Sunday morning ever!',                  'Puri Bhaji',       true, now() - interval '30 days 13 hours'),
('Nitin Jain',         5, 'I specifically sought out authentic Rajasthani food and found this gem. The dal baati churma was prepared traditionally and tasted exactly as it should. Pure bliss!',              'Dal Baati Churma', true, now() - interval '31 days 7 hours'),
('Aarti Malviya',      5, 'Food came beautifully packed and smelled amazing before I even opened it. The lauki ki sabzi and rotis were so comforting. Reminded me of winters at my grandma''s house.',       'Lauki Ki Sabzi',   true, now() - interval '33 days 10 hours'),
('Sumit Agarwal',      5, 'Itna pyaar se banaya hua khana bohot kam milta hai. Rajeshwari ji ne special note ke saath bheja ki kadhi ko thoda warm karke khao — that personal care makes all the difference!', 'Kadhi',            true, now() - interval '35 days 3 hours'),
('Ritu Choudhary',     5, 'Ordered a get-together spread for 30 people and everyone was asking where I got the food from. The moong dal halwa was the star of the evening. Absolutely unforgettable!',       'Moong Dal Halwa',  true, now() - interval '36 days 9 hours'),
('Varun Kapoor',       5, 'The paneer tikka was juicy, well-marinated and perfectly spiced. Even better than what I get at fancy restaurants, and delivered right to my door. Amazing value!',               'Paneer Tikka',     true, now() - interval '38 days 6 hours'),
('Nidhi Verma',        5, 'Been ordering every Sunday for the past 2 months. My Sunday feels incomplete without Saas Bahu Ki Rasoi''s khana. The consistency in taste and quality is remarkable!',           null,               true, now() - interval '40 days 11 hours'),
('Ajay Sharma',        5, 'The bessan gatte ki sabzi was made exactly the way it is done in Rajasthan — not the watered-down version you get elsewhere. Authentic and absolutely delicious!',                'Gatte Ki Sabzi',   true, now() - interval '41 days 4 hours'),
('Preeti Bansal',      5, 'Ek word mein boluun — LOVE! The food is made with so much heart. The baingan bharta had that proper smoky flavour from roasting. My husband had two helpings!',                   'Baingan Bharta',   true, now() - interval '43 days 14 hours'),
('Mohit Gupta',        5, 'I tried this on a friend''s recommendation and I am so grateful! The saag paneer was rich, creamy and paired beautifully with the soft makki ki roti. Will return!',              'Saag Paneer',      true, now() - interval '44 days 7 hours'),
('Geeta Sharma',       5, 'My mother-in-law visited and I was worried about impressing her with food. Ordered from here and she was so happy she asked for the number to order herself next time! 😊',        null,               true, now() - interval '46 days 5 hours'),
('Sandeep Mathur',     5, 'The mixed dal tadka had perfect balance of spices — not too hot, not too mild. Combined with the ghee-laden baati, it was a heavenly meal. Pure Rajasthani soul food!',           'Dal Tadka',        true, now() - interval '47 days 10 hours'),
('Ishaan Khanna',      5, 'Yaar kya khana hai! The aloo paratha was thick, stuffed generously, and tasted like mom made it. The homemade butter on top was the perfect finishing touch.',                   'Aloo Paratha',     true, now() - interval '49 days 2 hours'),
('Monika Tiwari',      5, 'Every bite feels like a warm hug. The food is prepared with such love and skill. The shahi paneer was rich and creamy — restaurant quality at home price. 5 stars easily!',      'Shahi Paneer',     true, now() - interval '50 days 8 hours'),
('Tarun Rajput',       5, 'Ordered kheer for a pooja at home and Veena ji made sure it had the right sweetness and garnish. She even asked about the occasion! That kind of personal service is priceless.',  'Kheer',            true, now() - interval '52 days 6 hours'),
('Varsha Goyal',       5, 'Three generations of my family ate together — my dadi, my parents, me and my kids — and every one of them loved the food. That is the true test of authentic taste!',             null,               true, now() - interval '53 days 12 hours'),
('Arjun Srivastava',   5, 'I work long hours and coming home to this food is honestly the highlight of my day. The pyaaz ki kachori was flaky, crispy and absolutely delicious. Highly recommend!',          'Pyaaz Ki Kachori', true, now() - interval '55 days 3 hours'),
('Sunaina Rastogi',    5, 'Maine sabse pehle dal makhani try ki aur ab koi bhi restaurant ka dal makhani achi nahi lagti! Addiction lag gayi hai is khane ki. Thank you so much! 😍',                        'Dal Makhani',      true, now() - interval '56 days 9 hours'),
('Kiran Malhotra',     5, 'The food arrived beautifully packed and still warm. The aloo tamatar ki sabzi and fresh rotis — it was just like Sunday lunch at my aunt''s place in Lucknow. Perfection!',       'Aloo Tamatar',     true, now() - interval '58 days 5 hours'),
('Praveen Dubey',      5, 'Tried the Rajasthani special thali for the first time and I cannot imagine eating anything else this weekend. Everything from the ker sangri to the churma was flawless!',          null,               true, now() - interval '60 days 11 hours'),
('Leena Agarwal',      5, 'My husband usually complains about home delivery food being too oily or too bland. He ate three rotis and asked me to order double next time! Best feedback I could share! 😄',    null,               true, now() - interval '62 days 7 hours'),
('Vivek Chaturvedi',   5, 'What truly sets this apart is the consistency. 6 orders over 2 months and the taste has been identical each time — perfectly spiced, perfectly cooked, perfectly fresh.',          null,               true, now() - interval '64 days 4 hours'),
('Ananya Patel',       5, 'The mango lassi was thick, creamy and tasted of real mangoes — not essence. Paired with the paneer kathi roll, it was an absolutely satisfying meal. Will order every week!',     'Mango Lassi',      true, now() - interval '66 days 13 hours'),
('Suresh Agarwal',     5, 'Main ek chef hoon aur main keh sakta hoon ki is khane mein asli technique aur love dono hain. The masalas are ground fresh, you can tell. Outstanding quality, no shortcuts.',   null,               true, now() - interval '68 days 6 hours'),
('Bhavna Chauhan',     5, 'Placed my order at 11 AM and food arrived perfectly on time. Hot, fresh, beautifully packed. The stuffed mirchi and baati combo was out of this world. Absolutely loved it!',     'Dal Baati Churma', true, now() - interval '70 days 9 hours'),
('Ashok Bansal',       5, 'Rajeshwari ji sent a handwritten note with my order wishing my daughter on her birthday. Such warmth and personal care is why I will never order from anywhere else! 🎂',         null,               true, now() - interval '72 days 3 hours'),
('Divyanka Sharma',    5, 'The food is exactly what the name promises — cooked like saas and bahu together with love and tradition. The rajma chawal was so comforting on a rainy day. 100 out of 100!',    'Rajma Chawal',     true, now() - interval '74 days 8 hours'),

-- ── 4-star reviews ────────────────────────────────────────────────────────────

('Nikhil Joshi',       4, 'Really good food overall — the dal fry and rotis were excellent. Delivery took a bit longer than expected but the taste made up for it completely. Will definitely order again!',  'Dal Fry',          true, now() - interval '9 days 15 hours'),
('Prachi Agarwal',     4, 'The paneer sabzi was flavourful and fresh. I would have given 5 stars but my order arrived slightly cold — probably because I live a bit far. The taste itself was perfect though!', 'Paneer Sabzi',     true, now() - interval '27 days 16 hours');

